_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 30
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
            "3":
                - 13
                - 23
                - 24
                - 55
            "4": 3.10.15
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
