_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 30
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
